/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import controller.*;
import java.util.*;
import java.awt.Color;

import javax.swing.JOptionPane;
import javax.swing.table.*;
import model.Juri;
/**
 *
 * @author Alief
 */
public class DashboardJuri_fix extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardJuri_fix.class.getName());

    /**
     * Creates new form DashboardJuri_fix
     */
    public DashboardJuri_fix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgDashboardPanit = new javax.swing.JPanel();
        jSplitPanePanitia = new javax.swing.JSplitPane();
        leftPanelside = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerTxt = new javax.swing.JLabel();
        navbarBox = new javax.swing.JPanel();
        menuNavbar = new javax.swing.JPanel();
        PesertaStatistik = new javax.swing.JPanel();
        statistikPeserta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        penilaianPeserta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutTxt = new javax.swing.JLabel();
        kontenPanel = new javax.swing.JPanel();
        rightpanelStatistik = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        headerNavbar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        boxPerkembanganpeserta = new javax.swing.JPanel();
        boxPaneltabel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelStatistikLomba = new javax.swing.JTable();
        boxCard = new javax.swing.JPanel();
        cardTotalPeserta = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        totalPesertatxt = new javax.swing.JLabel();
        cardTotalJuri = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        totalJuritxt = new javax.swing.JLabel();
        cardTotalLomba = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        totalLombatxt = new javax.swing.JLabel();
        boxRefresh = new javax.swing.JPanel();
        refreshBtnStatistik1 = new javax.swing.JButton();
        rightPanelPenilaian = new javax.swing.JPanel();
        headerNavbar1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        boxCRUDjuri = new javax.swing.JPanel();
        boxtabelNilai = new javax.swing.JPanel();
        scrollTabeljuri = new javax.swing.JScrollPane();
        tabelJuri = new javax.swing.JTable();
        boxActJuri = new javax.swing.JPanel();
        boxFieldJuri = new javax.swing.JPanel();
        inputNilaiLabel = new javax.swing.JLabel();
        fieldBeriNilai = new javax.swing.JTextField();
        boxBtnAddnilai = new javax.swing.JPanel();
        beriNilaiBtn = new javax.swing.JButton();
        boxSouthFilter = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Juri");

        bgDashboardPanit.setLayout(new java.awt.BorderLayout());

        jSplitPanePanitia.setDividerLocation(250);
        jSplitPanePanitia.setDividerSize(0);
        jSplitPanePanitia.setPreferredSize(new java.awt.Dimension(1100, 475));

        leftPanelside.setBackground(new java.awt.Color(0, 102, 0));
        leftPanelside.setMinimumSize(new java.awt.Dimension(250, 475));
        leftPanelside.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(0, 85, 15));
        headerPanel.setMinimumSize(new java.awt.Dimension(250, 50));
        headerPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        headerPanel.setLayout(new java.awt.BorderLayout());

        headerTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerTxt.setForeground(new java.awt.Color(255, 255, 255));
        headerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerTxt.setText("Dashboard Juri");
        headerPanel.add(headerTxt, java.awt.BorderLayout.CENTER);

        leftPanelside.add(headerPanel, java.awt.BorderLayout.NORTH);

        navbarBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        navbarBox.setOpaque(false);
        navbarBox.setLayout(new java.awt.BorderLayout());

        menuNavbar.setMinimumSize(new java.awt.Dimension(250, 350));
        menuNavbar.setOpaque(false);
        menuNavbar.setPreferredSize(new java.awt.Dimension(250, 350));
        menuNavbar.setLayout(new java.awt.GridBagLayout());

        PesertaStatistik.setBackground(new java.awt.Color(0, 102, 0));
        PesertaStatistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PesertaStatistikMousePressed(evt);
            }
        });
        PesertaStatistik.setLayout(new java.awt.GridBagLayout());

        statistikPeserta.setBackground(new java.awt.Color(0, 76, 6));
        statistikPeserta.setMinimumSize(new java.awt.Dimension(250, 50));
        statistikPeserta.setPreferredSize(new java.awt.Dimension(250, 50));
        statistikPeserta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statistikPesertaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statistikPesertaMousePressed(evt);
            }
        });
        statistikPeserta.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/monitoring_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel1.setText("Statistik Peserta");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(16);
        jLabel1.setMaximumSize(new java.awt.Dimension(225, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(225, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(225, 30));
        statistikPeserta.add(jLabel1, new java.awt.GridBagConstraints());

        PesertaStatistik.add(statistikPeserta, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        menuNavbar.add(PesertaStatistik, gridBagConstraints);

        penilaianPeserta.setBackground(new java.awt.Color(0, 102, 0));
        penilaianPeserta.setMinimumSize(new java.awt.Dimension(250, 50));
        penilaianPeserta.setPreferredSize(new java.awt.Dimension(250, 50));
        penilaianPeserta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                penilaianPesertaMousePressed(evt);
            }
        });
        penilaianPeserta.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel7.setText("Penilaian Peserta");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIconTextGap(16);
        jLabel7.setMaximumSize(new java.awt.Dimension(225, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(225, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(225, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 25);
        penilaianPeserta.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        menuNavbar.add(penilaianPeserta, gridBagConstraints);

        navbarBox.add(menuNavbar, java.awt.BorderLayout.NORTH);

        leftPanelside.add(navbarBox, java.awt.BorderLayout.CENTER);

        logoutPanel.setBackground(new java.awt.Color(0, 85, 6));
        logoutPanel.setMinimumSize(new java.awt.Dimension(250, 50));
        logoutPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutPanelMousePressed(evt);
            }
        });
        logoutPanel.setLayout(new java.awt.GridBagLayout());

        logoutTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutTxt.setForeground(new java.awt.Color(255, 255, 255));
        logoutTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        logoutTxt.setText("Logout");
        logoutTxt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoutTxt.setIconTextGap(16);
        logoutTxt.setMaximumSize(new java.awt.Dimension(225, 30));
        logoutTxt.setMinimumSize(new java.awt.Dimension(225, 30));
        logoutTxt.setPreferredSize(new java.awt.Dimension(225, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 25);
        logoutPanel.add(logoutTxt, gridBagConstraints);

        leftPanelside.add(logoutPanel, java.awt.BorderLayout.SOUTH);

        jSplitPanePanitia.setLeftComponent(leftPanelside);

        kontenPanel.setPreferredSize(new java.awt.Dimension(850, 475));
        kontenPanel.setLayout(new java.awt.CardLayout());

        rightpanelStatistik.setBackground(new java.awt.Color(255, 255, 255));
        rightpanelStatistik.setMinimumSize(new java.awt.Dimension(850, 475));
        rightpanelStatistik.setLayout(new java.awt.BorderLayout());

        topPanel.setOpaque(false);
        topPanel.setLayout(new java.awt.BorderLayout());

        headerNavbar.setBackground(new java.awt.Color(0, 102, 0));
        headerNavbar.setMinimumSize(new java.awt.Dimension(850, 50));
        headerNavbar.setPreferredSize(new java.awt.Dimension(850, 50));
        headerNavbar.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Statistik Peserta");
        headerNavbar.add(jLabel6, java.awt.BorderLayout.CENTER);

        topPanel.add(headerNavbar, java.awt.BorderLayout.NORTH);

        rightpanelStatistik.add(topPanel, java.awt.BorderLayout.NORTH);

        boxPerkembanganpeserta.setMinimumSize(new java.awt.Dimension(825, 275));
        boxPerkembanganpeserta.setOpaque(false);
        boxPerkembanganpeserta.setLayout(new java.awt.BorderLayout());

        boxPaneltabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 20, 20));
        boxPaneltabel.setOpaque(false);
        boxPaneltabel.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setMinimumSize(new java.awt.Dimension(825, 275));

        tabelStatistikLomba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Lomba", "Total Peserta", "Kuota"
            }
        ));
        tabelStatistikLomba.setMinimumSize(new java.awt.Dimension(825, 275));
        tabelStatistikLomba.setRowHeight(25);
        tabelStatistikLomba.setShowGrid(true);
        jScrollPane3.setViewportView(tabelStatistikLomba);

        boxPaneltabel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        boxPerkembanganpeserta.add(boxPaneltabel, java.awt.BorderLayout.CENTER);

        boxCard.setMinimumSize(new java.awt.Dimension(850, 125));
        boxCard.setOpaque(false);
        boxCard.setPreferredSize(new java.awt.Dimension(850, 125));
        boxCard.setLayout(new java.awt.GridBagLayout());

        cardTotalPeserta.setBackground(new java.awt.Color(0, 102, 0));
        cardTotalPeserta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cardTotalPeserta.setMinimumSize(new java.awt.Dimension(175, 100));
        cardTotalPeserta.setPreferredSize(new java.awt.Dimension(175, 100));
        cardTotalPeserta.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 76, 6));
        jPanel8.setMinimumSize(new java.awt.Dimension(175, 35));
        jPanel8.setPreferredSize(new java.awt.Dimension(175, 35));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total Peserta");
        jPanel8.add(jLabel8, java.awt.BorderLayout.CENTER);

        cardTotalPeserta.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel10.setMinimumSize(new java.awt.Dimension(175, 65));
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout());
        cardTotalPeserta.add(jPanel10, java.awt.BorderLayout.SOUTH);

        totalPesertatxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalPesertatxt.setForeground(new java.awt.Color(255, 255, 255));
        totalPesertatxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPesertatxt.setText("100");
        cardTotalPeserta.add(totalPesertatxt, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        boxCard.add(cardTotalPeserta, gridBagConstraints);

        cardTotalJuri.setBackground(new java.awt.Color(0, 102, 0));
        cardTotalJuri.setMinimumSize(new java.awt.Dimension(175, 100));
        cardTotalJuri.setPreferredSize(new java.awt.Dimension(175, 100));
        cardTotalJuri.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(0, 76, 6));
        jPanel12.setMinimumSize(new java.awt.Dimension(175, 35));
        jPanel12.setPreferredSize(new java.awt.Dimension(175, 35));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total Juri");
        jPanel12.add(jLabel9, java.awt.BorderLayout.CENTER);

        cardTotalJuri.add(jPanel12, java.awt.BorderLayout.NORTH);

        jPanel13.setMinimumSize(new java.awt.Dimension(175, 65));
        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.BorderLayout());
        cardTotalJuri.add(jPanel13, java.awt.BorderLayout.SOUTH);

        totalJuritxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalJuritxt.setForeground(new java.awt.Color(255, 255, 255));
        totalJuritxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalJuritxt.setText("100");
        cardTotalJuri.add(totalJuritxt, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        boxCard.add(cardTotalJuri, gridBagConstraints);

        cardTotalLomba.setBackground(new java.awt.Color(0, 102, 0));
        cardTotalLomba.setMinimumSize(new java.awt.Dimension(175, 100));
        cardTotalLomba.setPreferredSize(new java.awt.Dimension(175, 100));
        cardTotalLomba.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(0, 76, 6));
        jPanel14.setMinimumSize(new java.awt.Dimension(175, 35));
        jPanel14.setPreferredSize(new java.awt.Dimension(175, 35));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total Lomba");
        jPanel14.add(jLabel11, java.awt.BorderLayout.CENTER);

        cardTotalLomba.add(jPanel14, java.awt.BorderLayout.NORTH);

        jPanel15.setMinimumSize(new java.awt.Dimension(175, 65));
        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.BorderLayout());
        cardTotalLomba.add(jPanel15, java.awt.BorderLayout.SOUTH);

        totalLombatxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalLombatxt.setForeground(new java.awt.Color(255, 255, 255));
        totalLombatxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLombatxt.setText("100");
        cardTotalLomba.add(totalLombatxt, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        boxCard.add(cardTotalLomba, gridBagConstraints);

        boxRefresh.setMinimumSize(new java.awt.Dimension(100, 100));
        boxRefresh.setOpaque(false);
        boxRefresh.setLayout(new java.awt.CardLayout());

        refreshBtnStatistik1.setBackground(new java.awt.Color(0, 102, 0));
        refreshBtnStatistik1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreshBtnStatistik1.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtnStatistik1.setText("Refresh");
        refreshBtnStatistik1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshBtnStatistik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnStatistik1ActionPerformed(evt);
            }
        });
        boxRefresh.add(refreshBtnStatistik1, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        boxCard.add(boxRefresh, gridBagConstraints);

        boxPerkembanganpeserta.add(boxCard, java.awt.BorderLayout.NORTH);

        rightpanelStatistik.add(boxPerkembanganpeserta, java.awt.BorderLayout.CENTER);

        kontenPanel.add(rightpanelStatistik, "card2");

        rightPanelPenilaian.setBackground(new java.awt.Color(255, 255, 255));
        rightPanelPenilaian.setMinimumSize(new java.awt.Dimension(850, 475));
        rightPanelPenilaian.setLayout(new java.awt.BorderLayout());

        headerNavbar1.setBackground(new java.awt.Color(0, 102, 0));
        headerNavbar1.setMinimumSize(new java.awt.Dimension(850, 50));
        headerNavbar1.setPreferredSize(new java.awt.Dimension(850, 50));
        headerNavbar1.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Penilaian Peserta");
        headerNavbar1.add(jLabel14, java.awt.BorderLayout.CENTER);

        rightPanelPenilaian.add(headerNavbar1, java.awt.BorderLayout.NORTH);

        boxCRUDjuri.setMinimumSize(new java.awt.Dimension(825, 275));
        boxCRUDjuri.setOpaque(false);
        boxCRUDjuri.setPreferredSize(new java.awt.Dimension(825, 275));
        boxCRUDjuri.setLayout(new java.awt.BorderLayout());

        boxtabelNilai.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        boxtabelNilai.setOpaque(false);
        boxtabelNilai.setLayout(new java.awt.BorderLayout());

        scrollTabeljuri.setMinimumSize(new java.awt.Dimension(490, 600));
        scrollTabeljuri.setOpaque(false);
        scrollTabeljuri.setPreferredSize(new java.awt.Dimension(820, 1000));

        tabelJuri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Tajwid", "Fashahah", "Adab", "Suara Dan Lagu", "Penguasaan Juz"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelJuri.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tabelJuri.setMinimumSize(new java.awt.Dimension(400, 700));
        tabelJuri.setName(""); // NOI18N
        tabelJuri.setPreferredSize(new java.awt.Dimension(750, 700));
        tabelJuri.setRowHeight(25);
        tabelJuri.setSelectionBackground(new java.awt.Color(51, 153, 0));
        tabelJuri.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelJuri.setShowGrid(true);
        scrollTabeljuri.setViewportView(tabelJuri);

        boxtabelNilai.add(scrollTabeljuri, java.awt.BorderLayout.CENTER);

        boxCRUDjuri.add(boxtabelNilai, java.awt.BorderLayout.CENTER);

        boxActJuri.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        boxActJuri.setMinimumSize(new java.awt.Dimension(794, 89));
        boxActJuri.setOpaque(false);
        boxActJuri.setPreferredSize(new java.awt.Dimension(794, 89));
        boxActJuri.setLayout(new java.awt.BorderLayout());

        boxFieldJuri.setBackground(new java.awt.Color(204, 204, 204));
        boxFieldJuri.setMinimumSize(new java.awt.Dimension(50, 125));
        boxFieldJuri.setOpaque(false);
        boxFieldJuri.setPreferredSize(new java.awt.Dimension(50, 125));
        boxFieldJuri.setLayout(new java.awt.GridBagLayout());

        inputNilaiLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputNilaiLabel.setForeground(new java.awt.Color(0, 102, 0));
        inputNilaiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputNilaiLabel.setText("Masukkan nilai");
        inputNilaiLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        boxFieldJuri.add(inputNilaiLabel, gridBagConstraints);

        fieldBeriNilai.setBackground(new java.awt.Color(0, 102, 0));
        fieldBeriNilai.setForeground(new java.awt.Color(255, 255, 255));
        fieldBeriNilai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldBeriNilai.setMinimumSize(new java.awt.Dimension(200, 35));
        fieldBeriNilai.setPreferredSize(new java.awt.Dimension(200, 35));
        fieldBeriNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBeriNilaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        boxFieldJuri.add(fieldBeriNilai, gridBagConstraints);

        boxBtnAddnilai.setMinimumSize(new java.awt.Dimension(150, 30));
        boxBtnAddnilai.setPreferredSize(new java.awt.Dimension(150, 30));
        boxBtnAddnilai.setLayout(new java.awt.BorderLayout());

        beriNilaiBtn.setBackground(new java.awt.Color(0, 102, 0));
        beriNilaiBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        beriNilaiBtn.setForeground(new java.awt.Color(255, 255, 255));
        beriNilaiBtn.setText("Beri Nilai");
        beriNilaiBtn.setMargin(new java.awt.Insets(1, 15, 1, 15));
        beriNilaiBtn.setPreferredSize(new java.awt.Dimension(100, 20));
        beriNilaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beriNilaiBtnActionPerformed(evt);
            }
        });
        boxBtnAddnilai.add(beriNilaiBtn, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        boxFieldJuri.add(boxBtnAddnilai, gridBagConstraints);

        boxActJuri.add(boxFieldJuri, java.awt.BorderLayout.CENTER);

        boxCRUDjuri.add(boxActJuri, java.awt.BorderLayout.SOUTH);

        boxSouthFilter.setMinimumSize(new java.awt.Dimension(850, 50));
        boxSouthFilter.setOpaque(false);
        boxSouthFilter.setPreferredSize(new java.awt.Dimension(850, 50));
        boxSouthFilter.setLayout(new java.awt.GridBagLayout());

        jComboBox1.setBackground(new java.awt.Color(0, 102, 0));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(150, 30));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 25);
        boxSouthFilter.add(jComboBox1, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        boxSouthFilter.add(jButton1, gridBagConstraints);

        boxCRUDjuri.add(boxSouthFilter, java.awt.BorderLayout.NORTH);

        rightPanelPenilaian.add(boxCRUDjuri, java.awt.BorderLayout.CENTER);

        kontenPanel.add(rightPanelPenilaian, "card3");

        jSplitPanePanitia.setRightComponent(kontenPanel);

        bgDashboardPanit.add(jSplitPanePanitia, java.awt.BorderLayout.CENTER);

        getContentPane().add(bgDashboardPanit, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statistikPesertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistikPesertaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_statistikPesertaMouseClicked

    private void statistikPesertaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistikPesertaMousePressed

        rightpanelStatistik.setVisible(true);
        rightPanelPenilaian.setVisible(false);
        
        statistikPeserta.setBackground(new Color(0,76,6));
        penilaianPeserta.setBackground(new Color(0,102,0));
        
    }//GEN-LAST:event_statistikPesertaMousePressed

    private void PesertaStatistikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesertaStatistikMousePressed

    }//GEN-LAST:event_PesertaStatistikMousePressed

    private void penilaianPesertaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penilaianPesertaMousePressed
        // TODO add your handling code here:
        rightPanelPenilaian.setVisible(true);
        rightpanelStatistik.setVisible(false);
        
        penilaianPeserta.setBackground(new Color(0,76,6));
        statistikPeserta.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_penilaianPesertaMousePressed

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new login_fix().setVisible(true);
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void logoutPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutPanelMousePressed

    private void fieldBeriNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBeriNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBeriNilaiActionPerformed

    private void beriNilaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beriNilaiBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_beriNilaiBtnActionPerformed

    private void refreshBtnStatistik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnStatistik1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_refreshBtnStatistik1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardJuri_fix().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PesertaStatistik;
    private javax.swing.JButton beriNilaiBtn;
    private javax.swing.JPanel bgDashboardPanit;
    private javax.swing.JPanel boxActJuri;
    private javax.swing.JPanel boxBtnAddnilai;
    private javax.swing.JPanel boxCRUDjuri;
    private javax.swing.JPanel boxCard;
    private javax.swing.JPanel boxFieldJuri;
    private javax.swing.JPanel boxPaneltabel;
    private javax.swing.JPanel boxPerkembanganpeserta;
    private javax.swing.JPanel boxRefresh;
    private javax.swing.JPanel boxSouthFilter;
    private javax.swing.JPanel boxtabelNilai;
    private javax.swing.JPanel cardTotalJuri;
    private javax.swing.JPanel cardTotalLomba;
    private javax.swing.JPanel cardTotalPeserta;
    private javax.swing.JTextField fieldBeriNilai;
    private javax.swing.JPanel headerNavbar;
    private javax.swing.JPanel headerNavbar1;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerTxt;
    private javax.swing.JLabel inputNilaiLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPanePanitia;
    private javax.swing.JPanel kontenPanel;
    private javax.swing.JPanel leftPanelside;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel logoutTxt;
    private javax.swing.JPanel menuNavbar;
    private javax.swing.JPanel navbarBox;
    private javax.swing.JPanel penilaianPeserta;
    private javax.swing.JButton refreshBtnStatistik1;
    private javax.swing.JPanel rightPanelPenilaian;
    private javax.swing.JPanel rightpanelStatistik;
    private javax.swing.JScrollPane scrollTabeljuri;
    private javax.swing.JPanel statistikPeserta;
    private javax.swing.JTable tabelJuri;
    private javax.swing.JTable tabelStatistikLomba;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalJuritxt;
    private javax.swing.JLabel totalLombatxt;
    private javax.swing.JLabel totalPesertatxt;
    // End of variables declaration//GEN-END:variables
}
