/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import controller.*;
import java.util.*;
import java.awt.Color;

import javax.swing.JOptionPane;
import javax.swing.table.*;
import model.Juri;
/**
 *
 * @author Alief
 */
public class DashboardJuriCoba extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardJuriCoba.class.getName());

    /**
     * Creates new form DashboardJuriCoba
     */
    public DashboardJuriCoba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgDashboardPanit = new javax.swing.JPanel();
        jSplitPanePanitia = new javax.swing.JSplitPane();
        leftPanelside = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerTxt = new javax.swing.JLabel();
        navbarBox = new javax.swing.JPanel();
        menuNavbar = new javax.swing.JPanel();
        PesertaStatistik = new javax.swing.JPanel();
        statistikPeserta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        penilaianPeserta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutTxt = new javax.swing.JLabel();
        kontenPanel = new javax.swing.JPanel();
        rightpanelStatistik = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        headerNavbar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        boxCard = new javax.swing.JPanel();
        cardTotalPeserta = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        totalPesertatxt = new javax.swing.JLabel();
        boxRefresh = new javax.swing.JPanel();
        boxPerkembanganpeserta = new javax.swing.JPanel();
        boxPaneltabel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelStatistikLomba = new javax.swing.JTable();
        refreshBtnStatistik = new javax.swing.JButton();
        rightPanelPenilaian = new javax.swing.JPanel();
        headerNavbar1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        boxCRUDjuri = new javax.swing.JPanel();
        boxTabel = new javax.swing.JPanel();
        boxActJuri = new javax.swing.JPanel();
        refreshBox = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        boxFieldJuri = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        boxBtnJuriAct = new javax.swing.JPanel();
        addJuri = new javax.swing.JButton();
        editJuri = new javax.swing.JButton();
        leftBoxtabeljuri = new javax.swing.JPanel();
        scrollTabeljuri = new javax.swing.JScrollPane();
        tabelJuri = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgDashboardPanit.setLayout(new java.awt.BorderLayout());

        jSplitPanePanitia.setDividerLocation(250);
        jSplitPanePanitia.setDividerSize(0);
        jSplitPanePanitia.setPreferredSize(new java.awt.Dimension(1100, 475));

        leftPanelside.setBackground(new java.awt.Color(0, 102, 0));
        leftPanelside.setMinimumSize(new java.awt.Dimension(250, 475));
        leftPanelside.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(0, 85, 15));
        headerPanel.setMinimumSize(new java.awt.Dimension(250, 50));
        headerPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        headerPanel.setLayout(new java.awt.BorderLayout());

        headerTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerTxt.setForeground(new java.awt.Color(255, 255, 255));
        headerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerTxt.setText("Dashboard Juri");
        headerPanel.add(headerTxt, java.awt.BorderLayout.CENTER);

        leftPanelside.add(headerPanel, java.awt.BorderLayout.NORTH);

        navbarBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        navbarBox.setOpaque(false);
        navbarBox.setLayout(new java.awt.BorderLayout());

        menuNavbar.setMinimumSize(new java.awt.Dimension(250, 350));
        menuNavbar.setOpaque(false);
        menuNavbar.setPreferredSize(new java.awt.Dimension(250, 350));
        menuNavbar.setLayout(new java.awt.GridBagLayout());

        PesertaStatistik.setBackground(new java.awt.Color(0, 102, 0));
        PesertaStatistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PesertaStatistikMousePressed(evt);
            }
        });
        PesertaStatistik.setLayout(new java.awt.GridBagLayout());

        statistikPeserta.setBackground(new java.awt.Color(0, 76, 6));
        statistikPeserta.setMinimumSize(new java.awt.Dimension(250, 50));
        statistikPeserta.setPreferredSize(new java.awt.Dimension(250, 50));
        statistikPeserta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statistikPesertaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statistikPesertaMousePressed(evt);
            }
        });
        statistikPeserta.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/monitoring_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel1.setText("Statistik Peserta");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(16);
        jLabel1.setMaximumSize(new java.awt.Dimension(225, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(225, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(225, 30));
        statistikPeserta.add(jLabel1, new java.awt.GridBagConstraints());

        PesertaStatistik.add(statistikPeserta, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        menuNavbar.add(PesertaStatistik, gridBagConstraints);

        penilaianPeserta.setBackground(new java.awt.Color(0, 102, 0));
        penilaianPeserta.setMinimumSize(new java.awt.Dimension(250, 50));
        penilaianPeserta.setPreferredSize(new java.awt.Dimension(250, 50));
        penilaianPeserta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                penilaianPesertaMousePressed(evt);
            }
        });
        penilaianPeserta.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel7.setText("Aspek Penilaian");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIconTextGap(16);
        jLabel7.setMaximumSize(new java.awt.Dimension(225, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(225, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(225, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 25);
        penilaianPeserta.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        menuNavbar.add(penilaianPeserta, gridBagConstraints);

        navbarBox.add(menuNavbar, java.awt.BorderLayout.NORTH);

        leftPanelside.add(navbarBox, java.awt.BorderLayout.CENTER);

        logoutPanel.setBackground(new java.awt.Color(0, 85, 6));
        logoutPanel.setMinimumSize(new java.awt.Dimension(250, 50));
        logoutPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutPanelMousePressed(evt);
            }
        });
        logoutPanel.setLayout(new java.awt.GridBagLayout());

        logoutTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutTxt.setForeground(new java.awt.Color(255, 255, 255));
        logoutTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        logoutTxt.setText("Logout");
        logoutTxt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoutTxt.setIconTextGap(16);
        logoutTxt.setMaximumSize(new java.awt.Dimension(225, 30));
        logoutTxt.setMinimumSize(new java.awt.Dimension(225, 30));
        logoutTxt.setPreferredSize(new java.awt.Dimension(225, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 25);
        logoutPanel.add(logoutTxt, gridBagConstraints);

        leftPanelside.add(logoutPanel, java.awt.BorderLayout.SOUTH);

        jSplitPanePanitia.setLeftComponent(leftPanelside);

        kontenPanel.setPreferredSize(new java.awt.Dimension(850, 475));
        kontenPanel.setLayout(new java.awt.CardLayout());

        rightpanelStatistik.setBackground(new java.awt.Color(255, 255, 255));
        rightpanelStatistik.setMinimumSize(new java.awt.Dimension(850, 475));
        rightpanelStatistik.setLayout(new java.awt.BorderLayout());

        topPanel.setOpaque(false);
        topPanel.setLayout(new java.awt.BorderLayout());

        headerNavbar.setBackground(new java.awt.Color(0, 102, 0));
        headerNavbar.setMinimumSize(new java.awt.Dimension(850, 50));
        headerNavbar.setPreferredSize(new java.awt.Dimension(850, 50));
        headerNavbar.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Statistik Peserta");
        headerNavbar.add(jLabel6, java.awt.BorderLayout.CENTER);

        topPanel.add(headerNavbar, java.awt.BorderLayout.NORTH);

        boxCard.setMinimumSize(new java.awt.Dimension(850, 125));
        boxCard.setOpaque(false);
        boxCard.setPreferredSize(new java.awt.Dimension(850, 125));
        boxCard.setLayout(new java.awt.GridBagLayout());

        cardTotalPeserta.setBackground(new java.awt.Color(0, 102, 0));
        cardTotalPeserta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cardTotalPeserta.setMinimumSize(new java.awt.Dimension(175, 100));
        cardTotalPeserta.setPreferredSize(new java.awt.Dimension(175, 100));
        cardTotalPeserta.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 76, 6));
        jPanel8.setMinimumSize(new java.awt.Dimension(175, 35));
        jPanel8.setPreferredSize(new java.awt.Dimension(175, 35));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total Peserta");
        jPanel8.add(jLabel8, java.awt.BorderLayout.CENTER);

        cardTotalPeserta.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel10.setMinimumSize(new java.awt.Dimension(175, 65));
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout());
        cardTotalPeserta.add(jPanel10, java.awt.BorderLayout.SOUTH);

        totalPesertatxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalPesertatxt.setForeground(new java.awt.Color(255, 255, 255));
        totalPesertatxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPesertatxt.setText("100");
        cardTotalPeserta.add(totalPesertatxt, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        boxCard.add(cardTotalPeserta, gridBagConstraints);

        boxRefresh.setMinimumSize(new java.awt.Dimension(100, 100));
        boxRefresh.setOpaque(false);
        boxRefresh.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        boxCard.add(boxRefresh, gridBagConstraints);

        topPanel.add(boxCard, java.awt.BorderLayout.CENTER);

        rightpanelStatistik.add(topPanel, java.awt.BorderLayout.NORTH);

        boxPerkembanganpeserta.setMinimumSize(new java.awt.Dimension(825, 275));
        boxPerkembanganpeserta.setOpaque(false);
        boxPerkembanganpeserta.setLayout(new java.awt.BorderLayout());

        boxPaneltabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 20, 20));
        boxPaneltabel.setOpaque(false);
        boxPaneltabel.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setMinimumSize(new java.awt.Dimension(825, 275));

        tabelStatistikLomba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Lomba", "Total Peserta", "Kuota"
            }
        ));
        tabelStatistikLomba.setMinimumSize(new java.awt.Dimension(825, 275));
        tabelStatistikLomba.setRowHeight(25);
        tabelStatistikLomba.setShowGrid(true);
        jScrollPane3.setViewportView(tabelStatistikLomba);

        boxPaneltabel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        refreshBtnStatistik.setBackground(new java.awt.Color(0, 102, 0));
        refreshBtnStatistik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreshBtnStatistik.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtnStatistik.setText("Refresh");
        refreshBtnStatistik.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshBtnStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnStatistikActionPerformed(evt);
            }
        });
        boxPaneltabel.add(refreshBtnStatistik, java.awt.BorderLayout.PAGE_END);

        boxPerkembanganpeserta.add(boxPaneltabel, java.awt.BorderLayout.CENTER);

        rightpanelStatistik.add(boxPerkembanganpeserta, java.awt.BorderLayout.CENTER);

        kontenPanel.add(rightpanelStatistik, "card2");

        rightPanelPenilaian.setBackground(new java.awt.Color(255, 255, 255));
        rightPanelPenilaian.setMinimumSize(new java.awt.Dimension(850, 475));
        rightPanelPenilaian.setLayout(new java.awt.BorderLayout());

        headerNavbar1.setBackground(new java.awt.Color(0, 102, 0));
        headerNavbar1.setMinimumSize(new java.awt.Dimension(850, 50));
        headerNavbar1.setPreferredSize(new java.awt.Dimension(850, 50));
        headerNavbar1.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Statistik Peserta");
        headerNavbar1.add(jLabel14, java.awt.BorderLayout.CENTER);

        rightPanelPenilaian.add(headerNavbar1, java.awt.BorderLayout.NORTH);

        boxCRUDjuri.setMinimumSize(new java.awt.Dimension(825, 275));
        boxCRUDjuri.setOpaque(false);
        boxCRUDjuri.setPreferredSize(new java.awt.Dimension(825, 275));
        boxCRUDjuri.setLayout(new java.awt.BorderLayout());

        boxTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        boxTabel.setMinimumSize(new java.awt.Dimension(865, 275));
        boxTabel.setOpaque(false);
        boxTabel.setPreferredSize(new java.awt.Dimension(865, 275));
        boxTabel.setLayout(new java.awt.BorderLayout());

        boxActJuri.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        boxActJuri.setMinimumSize(new java.awt.Dimension(100, 150));
        boxActJuri.setOpaque(false);
        boxActJuri.setPreferredSize(new java.awt.Dimension(100, 150));
        boxActJuri.setLayout(new java.awt.BorderLayout());

        refreshBox.setLayout(new java.awt.CardLayout());

        btnRefresh.setBackground(new java.awt.Color(0, 102, 0));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setMinimumSize(new java.awt.Dimension(30, 23));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        refreshBox.add(btnRefresh, "card2");

        boxActJuri.add(refreshBox, java.awt.BorderLayout.NORTH);

        boxFieldJuri.setBackground(new java.awt.Color(204, 204, 204));
        boxFieldJuri.setMinimumSize(new java.awt.Dimension(50, 125));
        boxFieldJuri.setOpaque(false);
        boxFieldJuri.setPreferredSize(new java.awt.Dimension(50, 125));
        boxFieldJuri.setLayout(new java.awt.GridBagLayout());

        namaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(0, 102, 0));
        namaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLabel.setText("Masukkan nilai");
        namaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        boxFieldJuri.add(namaLabel, gridBagConstraints);

        fieldNama.setBackground(new java.awt.Color(0, 102, 0));
        fieldNama.setForeground(new java.awt.Color(255, 255, 255));
        fieldNama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldNama.setMinimumSize(new java.awt.Dimension(200, 35));
        fieldNama.setPreferredSize(new java.awt.Dimension(200, 35));
        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        boxFieldJuri.add(fieldNama, gridBagConstraints);

        boxActJuri.add(boxFieldJuri, java.awt.BorderLayout.CENTER);

        boxBtnJuriAct.setOpaque(false);
        boxBtnJuriAct.setLayout(new java.awt.GridBagLayout());

        addJuri.setBackground(new java.awt.Color(0, 102, 0));
        addJuri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addJuri.setForeground(new java.awt.Color(255, 255, 255));
        addJuri.setText("Tambah");
        addJuri.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addJuri.setMargin(new java.awt.Insets(2, 10, 2, 10));
        addJuri.setPreferredSize(new java.awt.Dimension(100, 22));
        addJuri.setRequestFocusEnabled(false);
        addJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJuriActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        boxBtnJuriAct.add(addJuri, gridBagConstraints);

        editJuri.setBackground(new java.awt.Color(0, 102, 0));
        editJuri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editJuri.setForeground(new java.awt.Color(255, 255, 255));
        editJuri.setText("Edit");
        editJuri.setMargin(new java.awt.Insets(1, 15, 1, 15));
        editJuri.setPreferredSize(new java.awt.Dimension(100, 20));
        editJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJuriActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        boxBtnJuriAct.add(editJuri, gridBagConstraints);

        boxActJuri.add(boxBtnJuriAct, java.awt.BorderLayout.PAGE_END);

        boxTabel.add(boxActJuri, java.awt.BorderLayout.SOUTH);

        leftBoxtabeljuri.setLayout(new java.awt.BorderLayout());
        boxTabel.add(leftBoxtabeljuri, java.awt.BorderLayout.WEST);

        scrollTabeljuri.setMinimumSize(new java.awt.Dimension(490, 600));
        scrollTabeljuri.setOpaque(false);
        scrollTabeljuri.setPreferredSize(new java.awt.Dimension(820, 1000));

        tabelJuri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Tajwid", "Fashahah", "Adab", "Suara Dan Lagu", "Penguasaan Juz"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelJuri.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tabelJuri.setMinimumSize(new java.awt.Dimension(400, 700));
        tabelJuri.setName(""); // NOI18N
        tabelJuri.setPreferredSize(new java.awt.Dimension(750, 700));
        tabelJuri.setRowHeight(25);
        tabelJuri.setSelectionBackground(new java.awt.Color(51, 153, 0));
        tabelJuri.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelJuri.setShowGrid(true);
        scrollTabeljuri.setViewportView(tabelJuri);

        boxTabel.add(scrollTabeljuri, java.awt.BorderLayout.CENTER);

        boxCRUDjuri.add(boxTabel, java.awt.BorderLayout.CENTER);

        rightPanelPenilaian.add(boxCRUDjuri, java.awt.BorderLayout.CENTER);

        kontenPanel.add(rightPanelPenilaian, "card3");

        jSplitPanePanitia.setRightComponent(kontenPanel);

        bgDashboardPanit.add(jSplitPanePanitia, java.awt.BorderLayout.CENTER);

        getContentPane().add(bgDashboardPanit, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statistikPesertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistikPesertaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_statistikPesertaMouseClicked

    private void statistikPesertaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistikPesertaMousePressed
        rightPanelPenilaian.setVisible(false);
        rightpanelStatistik.setVisible(true);
        
        PesertaStatistik.setBackground(new Color(0,76,6));
        penilaianPeserta.setBackground(new Color(0,102,0));
        
    }//GEN-LAST:event_statistikPesertaMousePressed

    private void PesertaStatistikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesertaStatistikMousePressed

    }//GEN-LAST:event_PesertaStatistikMousePressed

    private void penilaianPesertaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penilaianPesertaMousePressed
        // TODO add your handling code here:
        rightPanelPenilaian.setVisible(true);
        rightpanelStatistik.setVisible(false);
        
        penilaianPeserta.setBackground(new Color(0,76,6));
        PesertaStatistik.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_penilaianPesertaMousePressed

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new login_fix().setVisible(true);
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void logoutPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutPanelMousePressed

    private void refreshBtnStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnStatistikActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_refreshBtnStatistikActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void addJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJuriActionPerformed

    }//GEN-LAST:event_addJuriActionPerformed

    private void editJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJuriActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_editJuriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardJuriCoba().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PesertaStatistik;
    private javax.swing.JButton addJuri;
    private javax.swing.JPanel bgDashboardPanit;
    private javax.swing.JPanel boxActJuri;
    private javax.swing.JPanel boxBtnJuriAct;
    private javax.swing.JPanel boxCRUDjuri;
    private javax.swing.JPanel boxCard;
    private javax.swing.JPanel boxFieldJuri;
    private javax.swing.JPanel boxPaneltabel;
    private javax.swing.JPanel boxPerkembanganpeserta;
    private javax.swing.JPanel boxRefresh;
    private javax.swing.JPanel boxTabel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel cardTotalPeserta;
    private javax.swing.JButton editJuri;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JPanel headerNavbar;
    private javax.swing.JPanel headerNavbar1;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPanePanitia;
    private javax.swing.JPanel kontenPanel;
    private javax.swing.JPanel leftBoxtabeljuri;
    private javax.swing.JPanel leftPanelside;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel logoutTxt;
    private javax.swing.JPanel menuNavbar;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPanel navbarBox;
    private javax.swing.JPanel penilaianPeserta;
    private javax.swing.JPanel refreshBox;
    private javax.swing.JButton refreshBtnStatistik;
    private javax.swing.JPanel rightPanelPenilaian;
    private javax.swing.JPanel rightpanelStatistik;
    private javax.swing.JScrollPane scrollTabeljuri;
    private javax.swing.JPanel statistikPeserta;
    private javax.swing.JTable tabelJuri;
    private javax.swing.JTable tabelStatistikLomba;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalPesertatxt;
    // End of variables declaration//GEN-END:variables
}
