/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ui;

/**
 *
 * @author baiha
 */
public class dashboardJuri extends javax.swing.JFrame {

    /** Creates new form dashboardPanitia */
    public dashboardJuri() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDashboardPanitia = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        headerSideleft = new javax.swing.JPanel();
        textHeaderLeft = new javax.swing.JLabel();
        navbarLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dahsboard Juri");
        setMinimumSize(new java.awt.Dimension(1100, 475));

        bgDashboardPanitia.setMinimumSize(new java.awt.Dimension(1100, 475));
        bgDashboardPanitia.setPreferredSize(new java.awt.Dimension(1100, 475));
        bgDashboardPanitia.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1100, 475));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1100, 475));

        leftPanel.setBackground(new java.awt.Color(0, 102, 0));
        leftPanel.setMinimumSize(new java.awt.Dimension(250, 475));
        leftPanel.setPreferredSize(new java.awt.Dimension(250, 475));
        leftPanel.setLayout(new java.awt.BorderLayout());

        headerSideleft.setBackground(new java.awt.Color(0, 76, 9));
        headerSideleft.setMinimumSize(new java.awt.Dimension(250, 50));
        headerSideleft.setPreferredSize(new java.awt.Dimension(250, 50));
        headerSideleft.setLayout(new java.awt.GridBagLayout());

        textHeaderLeft.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textHeaderLeft.setForeground(new java.awt.Color(255, 255, 255));
        textHeaderLeft.setText("Dahsboard Juri");
        headerSideleft.add(textHeaderLeft, new java.awt.GridBagConstraints());

        leftPanel.add(headerSideleft, java.awt.BorderLayout.NORTH);

        navbarLeft.setOpaque(false);
        navbarLeft.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        navbarLeft.add(jPanel1, new java.awt.GridBagConstraints());

        leftPanel.add(navbarLeft, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setMinimumSize(new java.awt.Dimension(850, 475));
        rightPanel.setPreferredSize(new java.awt.Dimension(850, 475));
        rightPanel.setLayout(new java.awt.GridBagLayout());
        jSplitPane1.setRightComponent(rightPanel);

        bgDashboardPanitia.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(bgDashboardPanitia, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardJuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardJuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardJuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardJuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardJuri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgDashboardPanitia;
    private javax.swing.JPanel headerSideleft;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel navbarLeft;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel textHeaderLeft;
    // End of variables declaration//GEN-END:variables

}
