/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;


import controller.loginController;
import model.*;
/**
 *
 * @author baiha
 */
public class login_fix extends javax.swing.JFrame {

    /**
     * Creates new form login_fix
     */
    public login_fix() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        bg = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        sideleft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sideright = new javax.swing.JPanel();
        containerLogin = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        username_Label = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameLogin = new javax.swing.JTextField();
        passwordLogin = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setMinimumSize(new java.awt.Dimension(650, 400));
        setName("loginFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(650, 400));

        bg.setMinimumSize(new java.awt.Dimension(650, 400));
        bg.setOpaque(false);
        bg.setPreferredSize(new java.awt.Dimension(650, 400));
        bg.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(650, 400));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(650, 400));

        sideleft.setBackground(new java.awt.Color(0, 102, 0));
        sideleft.setMinimumSize(new java.awt.Dimension(300, 400));
        sideleft.setPreferredSize(new java.awt.Dimension(300, 400));
        sideleft.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/2.png"))); // NOI18N
        jLabel1.setText("MTQ-APP");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sideleft.add(jLabel1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(sideleft);

        sideright.setBackground(new java.awt.Color(255, 255, 255));
        sideright.setMinimumSize(new java.awt.Dimension(250, 400));
        sideright.setPreferredSize(new java.awt.Dimension(250, 400));
        sideright.setLayout(new java.awt.GridBagLayout());

        containerLogin.setMinimumSize(new java.awt.Dimension(250, 200));
        containerLogin.setOpaque(false);
        containerLogin.setPreferredSize(new java.awt.Dimension(250, 250));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWeights = new double[] {0.0, 1.0};
        containerLogin.setLayout(jPanel1Layout);

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(0, 102, 51));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("LOGIN");
        loginLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        containerLogin.add(loginLabel, gridBagConstraints);

        username_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_Label.setForeground(new java.awt.Color(0, 102, 0));
        username_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username_Label.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        containerLogin.add(username_Label, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 102, 0));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passwordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        containerLogin.add(passwordLabel, gridBagConstraints);

        usernameLogin.setBackground(new java.awt.Color(0, 102, 0));
        usernameLogin.setForeground(new java.awt.Color(255, 255, 255));
        usernameLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        containerLogin.add(usernameLogin, gridBagConstraints);

        passwordLogin.setBackground(new java.awt.Color(0, 102, 0));
        passwordLogin.setForeground(new java.awt.Color(255, 255, 255));
        passwordLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        passwordLogin.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        containerLogin.add(passwordLogin, gridBagConstraints);

        buttonLogin.setBackground(new java.awt.Color(0, 102, 0));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Login");
        buttonLogin.setBorder(null);
        buttonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLogin.setMargin(new java.awt.Insets(5, 10, 10, 10));
        buttonLogin.setMaximumSize(new java.awt.Dimension(75, 30));
        buttonLogin.setMinimumSize(new java.awt.Dimension(75, 30));
        buttonLogin.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        containerLogin.add(buttonLogin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        sideright.add(containerLogin, gridBagConstraints);

        jSplitPane1.setRightComponent(sideright);

        bg.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLoginActionPerformed
        // TODO add your handling code here:
        
//     
    }//GEN-LAST:event_usernameLoginActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed

        
    String username = usernameLogin.getText();
    String password = new String(passwordLogin.getPassword());

    User user = loginController.login(username, password);

    if (user != null) {
        // Kalau inputan sudah sesuai dengan database, maka pindah frame
        javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil");
        this.dispose(); // tutup frame login
        // new dashboardPanitia().setVisible(true);

        if ("panitia".equalsIgnoreCase(user.getRole())) {
            new DashboardPanitia().setVisible(true);
        } else if ("juri".equalsIgnoreCase(user.getRole())) {
            new dashboardJuri().setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Role tidak dikenali.");
        }

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Username atau password salah.");
    }
        
     // TODO add your handling code here:   

    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_fix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_fix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_fix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_fix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_fix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPanel containerLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JPanel sideleft;
    private javax.swing.JPanel sideright;
    private javax.swing.JTextField usernameLogin;
    private javax.swing.JLabel username_Label;
    // End of variables declaration//GEN-END:variables
}
